#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Runs the beatification process by creating/populating the wiki, the gh-pages branch (coming-soon or launched), putting a static viewer. This can only be run after creating a pre-release branch. g-compile is used to build the static website"
def args_adder(parser):
    pass

def run(verbose):
    # Create a new wiki for the project
    """
    try: sh.ls("../" + name + ".wiki")
    except: git.cloneWiki(remote['name'], remote['clone_url'])
    # create new pages branch
    if not nopages :
        try: git.branchVerify("gh-pages")
        except:
            git.pagesBranch()

    # Push everything
    if not noremote :
        verbose("Pushing everything to remote")
        git.pushAll("Syncing Beautified Repo")
    return 0
    """
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
