#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Manages blog posts for jekyll. This can create, edit, or delete blog posts. By default, it always opens vim for input- including edits. When closing, this script will run a spell/grammer checker."
def args_adder(parser):
    pass

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
