#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a boilerplate code file for the specified langauge- essentially the same as vim <non-existing-file> except it will generate code that can be used to boilerplate development. This includes code to run from either commandline or as an include/module, and basic set-up of the file for that language. If a boilerplate.xx file is needed, but does not exist- it will be created."

def args_adder(parser):
    pass

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
