#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())


desc = "Opens the changes between this branch and the master side by side (runs icdiff, but shos full changes between this branch and master), useful on PR branches"
def args_adder(parser):
    parser.add_argument('-l', '--last', action='store_true',help="Shows only the changes since the last commit (eq to git icdiff)")
    parser.add_argument('-i', '--inline', action='store_true',help="Shows change inline opposed to split view")
    parser.add_argument('-b', '--branch', type=str,help="Compares the current branch to a branch other than dev")

def run(last, inline, branch, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
