#!/usr/bin/env python3
import os
import sys
import sh
import requests
import json
sys.path.append(os.getcwd())
import ghCommands as gitHub
import gitCommands as git

def checkStatus(dirName):
    local = git.isRepo(dirName)
    remote = gitHub.isRepo(dirName)
    if locale and not remote :
        gitHub.create(dirName)
        git.addRemote(dirName)
        git.pushAll()
    elif not local and remote :
        git.clone(remote['clone_url'])
    elif not local and not remote :
        created = gitHub.create(dirName)
        git.clone(created)
    elif local and remote :
        git.save()
        git.addRemote(remote['full_name'])
        git.fetch()
        git.pushAll()

def setupLocal():
    # Check for README
        # if no README || README > 1 line
        # Pull readme from https://gist.githubusercontent.com/jxson/1784669/raw/README.md
    # Check for .gitignore
        # if no .gitignore
            # Pull from https://www.gitignore.io/api/<lang>
    # Check for gh-pages branch
        # if no gh-pages branch
            # Copy from ./pages/coming_soon/<template>
    # Check for .wiki
        # if no .wiki
            # Clone wiki into ../<repo-name>.wiki

def main(args):
    if len(args) < 3 : # dirName lang description
    if args[0] == "./":
        dirName = os.getcwd().split("/")[-1]
    else :
        dirName = args[0]

    checkStatus(dirName)
    setupLocal(args)

if __name__ == '__main__':
    sys.exit(main(sys.argsv[1:]))
