#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Runs git bisect to find the source of a bug using a graphic"
def args_adder(parser):
    parser.add_arguments('start', type=str, help="A commit known to be prior to the introduction of the issue being searched for")

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
