#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a new Feature Branch off of the dev branch. Feature branches will be merged back into dev. FB- prefix"
def args_adder(parser):
    parser.add_argument('name', type=str,help="The name of the feature branch to be created, normally this is a numeric code associated with a ticket number.")

def run(name, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
