#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Allows easy work with open source development, starts by forking a repo on github, then runs the g-create script to set up the repository for you to use."
def args_adder(parser):
    pass

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
