#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a new install script that is appened to the user's existing install gist (as a new file). The install gist is a miniturized package manager for this particular user."
def args_adder(parser):
    pass

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
