#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())
"""
desc = "Creates a golf script in the dedicated Golf Script folder ~/Dev/Golf/ and creates the folder if needed"
    parser.add_argument('name', type=str,help="Name of the Golf Script")
    parser.add_argument('-d', '--desc', type=str,help="The problem descriptionm, including examples. if not set, vim will open to accept a description")
    parser.add_argument('--data', N, nargs="*",help="The data to be fed into the golf script for testing, if not provided, vim will open up to accept a dataset.")
    parser.add_argument('-n', '--nodata', action='store_true' ,help="If this variable is set, then it is assumed the script runs without arguements and vim will not open to accept a dataset")
"""

"""
desc = "Creates a new install script that is appened to the user's existing install gist (as a new file). The install gist is a miniturized package manager for this particular user."
"""

"""
desc = "Creates a 1 off user script for the user which is saved as a gist. Scripts are created in ~/Dev/Scripts/, which is then added to the path (and chmod +x is enabled)"
    parser.add_argument('name', type=str,help="The name of the script to be created")
    parser.add_argument('-l', '--lang', type=str,help="The Language for the script to use, the default is to create a bash script", default='sh')
"""
desc = "Creates a gist of the specified type [golf|install|script] including the appropriate information about it"
def args_adder(parser):
    pass

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
