#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a 1 off user script for the user which is saved as a gist. Scripts are created in ~/Dev/Scripts/, which is then added to the path (and chmod +x is enabled)"
def args_adder(parser):
    parser.add_argument('name', type=str,help="The name of the script to be created")
    parser.add_argument('-l', '--lang', type=str,help="The Language for the script to use, the default is to create a bash script", default='sh')

def run(name, lang, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
