#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a Hot Fix branch from the QA Branch. This branch will be merged back into QA and Dev. This type of branch is for small fixes to resolve a QA issue. The QA Branch should go live immediately."
def args_adder(parser):
    parser.add_argument('name', type=str,help="Name of the QA Hot Fix. This is normally the original issue number appened with -[a-z]")

def run(name, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
