#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a Hot Fix branch from the release, this branch will be merged back into release and dev, conflicts must be resolved on both branches before merging. "
def args_adder(parser):
    parser.add_argument('name', type=str,help="The name of the Hot Fix branch, normally this is an issue number")

def run(name, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
