#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Runs unit tests against the PR branch and marks them as 'passed by author' if they pass, or 'failed by author' if they fail."

def args_adder(parser):
    parser.add_argument('name', type=str,help="The name of the feature branch to be created, normally this is numeric code associate with a ticket")

def run(name, verbose):
    output = {};
    return output

def console(output, verbose):
    from termcolor import colored
    print(output)

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
