#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a unit test branch which can be used to build out unit tests for a PR. This is where g-PRtest should be used."
def args_adder(parser):
    pass

def run(verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
