#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Pulls down a given commit, allowing you to test out any changes- as well as comment on any changes within the diff"
def args_adder(parser):
    parser.add_argument('name', type=str,help="Name of the PR branch to review")

def run(name, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
