#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Rolls back the last n commits from this branch and the remote, creating a detached head with the changes- leaving the remote clean"
def args_adder(parser):
    parser.add_argument('-n', '--num', type=int,help="The number of remote commits to rollback")

def run(num, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
