#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Saves the changes by adding all and committing them. This can be used to push to remote, or push to remote and generate a PR directly from this line."
def args_adder(parser):
    parser.add_argument('-m', '--message',type=str, default=False, help="The message to commit with")
    parser.add_argument('-R', '--remote',action='store_false', help="Ready to save to remote")
    parser.add_argument('-P', '--pullrequest',action='store_false', help="Create a pull request (Automatically saves to remote as well")

def run(message=False, verbose=False):
    import gitCommands as git
    return git.save(message)

def console(output, verbose):
    print(output)

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
