#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Creates a new scripting branch and runs the appropriate script against it. If the script fails- the branch is stashed. If you are already on the scripting branch, then you stay on this branch"
def args_adder(parser):
    parser.add_argument('f', nargs='?', type=str,help="The file to execute on the cwd")
    parser.add_argument('-e', '--execute', type=str,help="The command to execute on the cwd")

def run(f, execute, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
