#!/usr/bin/env python3
import sys, os
sys.path.append(os.getcwd())

desc = "Squashes the last N commits into 1, if N is not provided, it will squash all commits going back to when this branch diverges. Squashes will not include any merge commits"
def args_adder(parser):
    parser.add_argument('-n', '--num', type=int,help="The Number of commits to squash")

def run(num, verbose):
    pass

def console(output, verbose):
    print output

#########################################################################
# Boiler plate code to create a new module / command line module to be used.
#########################################################################
import boilerplate
boilerplate.create(__name__, desc, args_adder, run, console)
